version: '3.8'

networks:
  my_network: {}

services:
  dispatcher-app:
    build: .
    container_name: dispatcher-app
    ports:
      - "8088:8088"
    depends_on:
      - postgres-db
      - rabbitmq
    networks:
      - my_network
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres-db:5432/postgres
      - SPRING_R2DBC_USERNAME=userok
      - SPRING_R2DBC_PASSWORD=12345
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=userok
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_RABBITMQ_HOST=my_rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=userok
      - SPRING_RABBITMQ_PASSWORD=p@ssw0rd
      - FOURSQUARE_API_KEY=fsq3SltC/PKY6e1XzBrB4qgrYeKRiVFTV/bvcVrTXdk5NdI=

  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: userok
      RABBITMQ_DEFAULT_PASS: p@ssw0rd
    networks:
      - my_network

volumes:
  postgres-data:
