server.port=8088

# Bot configuration properties
botConfig.token=
botConfig.name=you_want_food_use_Restaurant_bot
botConfig.url=https://92e5-92-61-67-115.ngrok-free.app


# RabbitMQ configuration properties
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=
spring.rabbitmq.password=
