spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration

server.port=8088

# Bot configuration
botConfig.token=6850710277:AAFGEC9MJNAbNOOvm2Zwrqduf0o3kUCIG1U
botConfig.name=you_want_food_use_Restaurant_bot
botConfig.url=https://92e5-92-61-67-115.ngrok-free.app

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=userok
spring.rabbitmq.password=p@ssw0rd

# PostgreSQL (R2DBC)
spring.r2dbc.url=r2dbc:postgresql://postgres-db:5432/postgres
spring.r2dbc.username=userok
spring.r2dbc.password=12345
spring.r2dbc.dialect=POSTGRESQL